package Utils;

public enum DiseaseType {
    CANINE_PARAVOVIRUS,
    RABIES,
    FELINE_LEUKEMIA,
    PSITTACOSIS,
    CANINE_DISTEMPER,
    HEARTWORM,
    LYME_DISEASE,
    KENNEL_COUGH,
    LEPTOSPIROSIS,
    CANINE_HEPATITIS,
    TICK_FEVER,
    BABESIOSIS,
    ANTHRAX,
    BRUCELLOSIS,
    RINGWORM

}
